import '@/lib/legacy-env';
import { NextResponse } from 'next/server';
import { imageEnabled, geminiEnabled, openrouterEnabled, deepseekEnabled, moonshotEnabled } from '@/src/config';
import { generateImageWithMeta, generateSvgSketch, getLastImageError } from '@/src/ai/providers';
import { requireTokens } from '@/lib/auth-guard';
import { NO_TEXT_RULE } from '@/lib/image-styles';
import { recordImageUsage } from '@/lib/usage-log';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
export const maxDuration = 45;

// Friendly display names for the generator, so the chat can attribute the image
// ("Generated by …") to whichever backend actually produced it.
const PROVIDER_LABEL: Record<string, string> = {
  gemini: 'Google Gemini (Nano Banana)',
  openai: 'OpenAI (gpt-image-1)',
  leonardo: 'Leonardo AI',
  grok: 'xAI Grok',
  replicate: 'Replicate',
  pollinations: 'Pollinations',
  sketch: 'SketchLearn (SVG sketch)',
};

// POST { prompt } -> { url, provider }
// Generates an AI image straight from the coach chat and reports WHICH generator
// made it, so the chat can show attribution. Costs the learner credits.
export async function POST(req: Request) {
  const a = await requireTokens(req);
  if (!a.ok) return a.response;
  const b = (await req.json().catch(() => ({}))) || {};
  const idea = String(b.prompt || '').slice(0, 500).trim();
  // "interpret" mode: no typed prompt required — the coach draws its own read of
  // the conversation so far as an anthropomorphic scene (a Polaroid keepsake).
  const mode = String(b.mode || '').trim();
  const convo = String(b.convo || '').slice(0, 1500).trim();
  const interpret = mode === 'interpret';
  if (!idea && !interpret) return NextResponse.json({ error: 'Tell me what to draw.' }, { status: 400 });

  if (!imageEnabled && !geminiEnabled && !openrouterEnabled && !deepseekEnabled && !moonshotEnabled) {
    return NextResponse.json({ error: 'No image model is configured.' }, { status: 200 });
  }

  const prompt = interpret
    ? [
        'A whimsical, warm hand-illustrated scene of friendly ANTHROPOMORPHIC animal characters (animals that walk, talk and gesture like people) — the coach\'s playful interpretation of a tutoring conversation.',
        'Show the characters acting out or surrounded by the ideas and topics being discussed, as if it were a candid snapshot of the lesson happening.',
        convo ? `The conversation so far (interpret its mood and subjects visually, do NOT write any of these words in the picture): ${convo}` : 'A learner and their animal coach chatting about what to study next.',
        idea ? `Extra direction from the learner: "${idea}".` : '',
        'Storybook illustration, gentle lighting, tasteful colour, expressive characters.',
        NO_TEXT_RULE,
      ].filter(Boolean).join(' ')
    : [
        'A warm, friendly, hand-illustrated educational picture — clean composition, tasteful colour, gentle lighting; the kind of image that helps a learner picture the idea.',
        `Draw this: "${idea}".`,
        NO_TEXT_RULE,
      ].join(' ');

  const GEN_BUDGET_MS = 38000;
  const timeout = <T,>(p: Promise<T>, ms: number) => Promise.race([
    p,
    new Promise<T>((_, reject) => setTimeout(() => reject(new Error('image-timeout')), ms)),
  ]);

  try {
    let url: string | null = null;
    let provider = '';
    try {
      const r: any = await timeout(generateImageWithMeta(prompt), GEN_BUDGET_MS);
      url = r?.url || null;
      provider = r?.provider || '';
      // No image model reachable — fall back to a hand-drawn SVG via the text model
      // so the chat still gets a picture rather than an error.
      if (!url) { url = await timeout((generateSvgSketch as any)(idea || 'our chat so far'), 12000); if (url) provider = 'sketch'; }
    } catch (e: any) {
      if (String(e?.message) === 'image-timeout') {
        return NextResponse.json({ error: 'The image generator is taking too long right now — please try again in a moment.' }, { status: 200 });
      }
      throw e;
    }
    if (!url) {
      const why = (typeof getLastImageError === 'function' && getLastImageError()) || '';
      return NextResponse.json({ error: why ? `Could not generate an image. ${String(why).slice(0, 400)}` : 'Could not generate an image — try again.' }, { status: 200 });
    }

    const subject = idea || (interpret ? 'chat interpretation' : '');
    await recordImageUsage({ username: a.user.username, kind: 'coach-image', provider, subject, meta: { prompt: subject, mode } });

    // Offload a data: URL to the blob store when configured, so we don't carry
    // megabytes of base64 around the chat.
    if (/^data:image\//i.test(url) && process.env.BLOB_READ_WRITE_TOKEN) {
      try {
        const m = url.match(/^data:(image\/[\w+.-]+);base64,(.+)$/);
        if (m) {
          const { put } = await import('@vercel/blob');
          const buf = Buffer.from(m[2], 'base64');
          const ext = (m[1].split('/')[1] || 'png').replace(/[^a-z0-9]/gi, '') || 'png';
          const blob = await put(`coach/${Date.now()}.${ext}`, buf, { access: 'public', addRandomSuffix: true, contentType: m[1] });
          url = blob.url;
        }
      } catch { /* keep the data URL */ }
    }

    return NextResponse.json({ url, provider, providerLabel: PROVIDER_LABEL[provider] || provider || 'AI' });
  } catch {
    return NextResponse.json({ error: 'Image generation failed.' }, { status: 200 });
  }
}
